//go:build linux

package adapter

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/bug3dev/sensync/internal/config"
	"github.com/bug3dev/sensync/internal/mapping"
)

type HyprlandAdapter struct {
	exec     Executor
	confPath string // e.g. $XDG_CONFIG_HOME/hypr/sensync.conf
}

// NewHyprlandAdapter constructs an adapter wired to ShellExecutor and the
// default config path under $XDG_CONFIG_HOME (or ~/.config).
func NewHyprlandAdapter() (*HyprlandAdapter, error) {
	if _, err := exec.LookPath("hyprctl"); err != nil {
		return nil, fmt.Errorf("hyprctl not found in PATH; sensync currently supports Hyprland only on Linux")
	}
	base := os.Getenv("XDG_CONFIG_HOME")
	if base == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return nil, fmt.Errorf("locate home dir: %w", err)
		}
		base = filepath.Join(home, ".config")
	}
	return &HyprlandAdapter{
		exec:     ShellExecutor{},
		confPath: filepath.Join(base, "hypr", "sensync.conf"),
	}, nil
}

func (a *HyprlandAdapter) Name() string { return "hyprland" }

func (a *HyprlandAdapter) BuildPlan(cfg config.Config) (Plan, error) {
	if err := os.MkdirAll(filepath.Dir(a.confPath), 0o755); err != nil {
		return Plan{}, fmt.Errorf("ensure conf dir: %w", err)
	}
	return hyprlandPlan(cfg, a.confPath)
}

// hyprlandPlan builds the Hyprland Plan without importing the plan sub-package
// (which imports this package, creating a cycle). Logic mirrors plan.Hyprland.
func hyprlandPlan(cfg config.Config, confPath string) (Plan, error) {
	var warnings []string
	if cfg.Mouse.Sensitivity != cfg.Trackpad.Sensitivity {
		warnings = append(warnings,
			fmt.Sprintf("hyprland: [mouse].sensitivity=%v differs from [trackpad].sensitivity=%v; Hyprland's input block is global, trackpad value will win",
				cfg.Mouse.Sensitivity, cfg.Trackpad.Sensitivity))
	}
	if cfg.Mouse.Acceleration != cfg.Trackpad.Acceleration {
		warnings = append(warnings,
			"hyprland: [mouse].acceleration differs from [trackpad].acceleration; trackpad value will win")
	}

	sens := mapping.HyprlandSensitivityFromMultiplier(cfg.Trackpad.Sensitivity)
	accelProfile := "flat"
	if cfg.Trackpad.Acceleration && cfg.Trackpad.Sensitivity == 1.0 {
		accelProfile = "adaptive"
	}

	conf := buildHyprConf(cfg, sens, accelProfile)
	steps := []Step{
		{
			Kind:   StepWriteFile,
			Target: confPath,
			Args:   []string{conf},
			Desc:   "write " + confPath,
		},
		{
			Kind:   StepExec,
			Target: "hyprctl",
			Args:   []string{"keyword", "input:sensitivity", strconv.FormatFloat(sens, 'f', -1, 64)},
			Desc:   "hyprctl input:sensitivity " + strconv.FormatFloat(sens, 'f', -1, 64),
		},
		{
			Kind:   StepExec,
			Target: "hyprctl",
			Args:   []string{"keyword", "input:accel_profile", accelProfile},
			Desc:   "hyprctl input:accel_profile " + accelProfile,
		},
		{
			Kind:   StepExec,
			Target: "hyprctl",
			Args:   []string{"keyword", "input:natural_scroll", strconv.FormatBool(cfg.Mouse.NaturalScroll)},
			Desc:   "hyprctl input:natural_scroll " + strconv.FormatBool(cfg.Mouse.NaturalScroll),
		},
		{
			Kind:   StepExec,
			Target: "hyprctl",
			Args:   []string{"keyword", "input:scroll_factor", strconv.FormatFloat(cfg.Mouse.ScrollSpeed, 'f', -1, 64)},
			Desc:   "hyprctl input:scroll_factor " + strconv.FormatFloat(cfg.Mouse.ScrollSpeed, 'f', -1, 64),
		},
		{
			Kind:   StepExec,
			Target: "hyprctl",
			Args:   []string{"keyword", "input:touchpad:natural_scroll", strconv.FormatBool(cfg.Trackpad.NaturalScroll)},
			Desc:   "hyprctl input:touchpad:natural_scroll " + strconv.FormatBool(cfg.Trackpad.NaturalScroll),
		},
	}
	return Plan{Steps: steps, Warnings: warnings}, nil
}

func buildHyprConf(cfg config.Config, sens float64, accelProfile string) string {
	var b strings.Builder
	b.WriteString("# Generated by sensync. Do not edit; this file is overwritten on every `sensync apply`.\n")
	b.WriteString("# Add `source = ~/.config/hypr/sensync.conf` (or wherever this lives) to your hyprland.conf.\n\n")
	b.WriteString("input {\n")
	fmt.Fprintf(&b, "    sensitivity = %s\n", strconv.FormatFloat(sens, 'f', -1, 64))
	fmt.Fprintf(&b, "    accel_profile = %s\n", accelProfile)
	fmt.Fprintf(&b, "    natural_scroll = %s\n", strconv.FormatBool(cfg.Mouse.NaturalScroll))
	fmt.Fprintf(&b, "    scroll_factor = %s\n", strconv.FormatFloat(cfg.Mouse.ScrollSpeed, 'f', -1, 64))
	b.WriteString("\n    touchpad {\n")
	fmt.Fprintf(&b, "        natural_scroll = %s\n", strconv.FormatBool(cfg.Trackpad.NaturalScroll))
	b.WriteString("    }\n")
	b.WriteString("}\n")
	return b.String()
}

func (a *HyprlandAdapter) Apply(p Plan, dryRun bool) (Result, error) {
	var res Result
	if dryRun {
		res.Applied = append(res.Applied, p.Steps...)
		return res, nil
	}
	for _, s := range p.Steps {
		if err := a.exec.Do(s); err != nil {
			res.Failed = append(res.Failed, FailedStep{Step: s, Err: err})
			continue
		}
		res.Applied = append(res.Applied, s)
	}
	return res, nil
}

func (a *HyprlandAdapter) Get() (config.Config, error) {
	cfg := config.Default()
	if v, err := readHyprctlFloat("input:sensitivity"); err == nil {
		cfg.Mouse.Sensitivity = v + 1.0
		cfg.Trackpad.Sensitivity = v + 1.0
	}
	// Acceleration, natural_scroll, and scroll_speed are not read in MVP; the
	// other config fields stay at Default() values so `get` output is still
	// valid TOML. A future task can extend this once a Hyprland Get path is
	// in scope.
	return cfg, nil
}

// readHyprctlFloat invokes `hyprctl -j getoption KEY` and extracts the
// `"float": X` field via a small string scan. We avoid encoding/json to keep
// dependencies minimal; the format is stable across Hyprland versions.
func readHyprctlFloat(key string) (float64, error) {
	out, err := exec.Command("hyprctl", "-j", "getoption", key).Output()
	if err != nil {
		return 0, fmt.Errorf("hyprctl getoption %s: %w", key, err)
	}
	raw := strings.ReplaceAll(string(out), "\n", " ")
	idx := strings.Index(raw, `"float":`)
	if idx < 0 {
		return 0, fmt.Errorf("hyprctl json: missing float field in %q", raw)
	}
	rest := raw[idx+len(`"float":`):]
	end := strings.IndexAny(rest, ",}")
	if end < 0 {
		return 0, fmt.Errorf("hyprctl json: malformed float field in %q", raw)
	}
	v, err := strconv.ParseFloat(strings.TrimSpace(rest[:end]), 64)
	if err != nil {
		return 0, fmt.Errorf("hyprctl json float parse: %w", err)
	}
	return v, nil
}
