package plan

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/bug3dev/sensync/internal/adapter/types"
	"github.com/bug3dev/sensync/internal/config"
	"github.com/bug3dev/sensync/internal/mapping"
)

// Hyprland builds a Plan for a Hyprland host. confPath is the absolute path
// to the `sensync.conf` file that will be written; the user must `source` it
// from their main hyprland.conf.
//
// Hyprland's `input { sensitivity = X }` is global across pointing devices.
// If the config asks for diverging mouse and trackpad sensitivity, a warning
// is emitted and trackpad values win (last-write within the generated block).
func Hyprland(cfg config.Config, confPath string) (types.Plan, error) {
	var warnings []string
	if cfg.Mouse.Sensitivity != cfg.Trackpad.Sensitivity {
		warnings = append(warnings,
			fmt.Sprintf("hyprland: [mouse].sensitivity=%v differs from [trackpad].sensitivity=%v; Hyprland's input block is global, trackpad value will win",
				cfg.Mouse.Sensitivity, cfg.Trackpad.Sensitivity))
	}
	if cfg.Mouse.Acceleration != cfg.Trackpad.Acceleration {
		warnings = append(warnings,
			"hyprland: [mouse].acceleration differs from [trackpad].acceleration; trackpad value will win")
	}

	// Trackpad values win because they are written second within the input block.
	sens := mapping.HyprlandSensitivityFromMultiplier(cfg.Trackpad.Sensitivity)
	accelProfile := "flat"
	if cfg.Trackpad.Acceleration && cfg.Trackpad.Sensitivity == 1.0 {
		accelProfile = "adaptive"
	}

	conf := buildHyprlandConf(cfg, sens, accelProfile)
	steps := []types.Step{
		{
			Kind:   types.StepWriteFile,
			Target: confPath,
			Args:   []string{conf},
			Desc:   "write " + confPath,
		},
		{
			Kind:   types.StepExec,
			Target: "hyprctl",
			Args:   []string{"keyword", "input:sensitivity", strconv.FormatFloat(sens, 'f', -1, 64)},
			Desc:   "hyprctl input:sensitivity " + strconv.FormatFloat(sens, 'f', -1, 64),
		},
		{
			Kind:   types.StepExec,
			Target: "hyprctl",
			Args:   []string{"keyword", "input:accel_profile", accelProfile},
			Desc:   "hyprctl input:accel_profile " + accelProfile,
		},
		{
			Kind:   types.StepExec,
			Target: "hyprctl",
			Args:   []string{"keyword", "input:natural_scroll", strconv.FormatBool(cfg.Mouse.NaturalScroll)},
			Desc:   "hyprctl input:natural_scroll " + strconv.FormatBool(cfg.Mouse.NaturalScroll),
		},
		{
			Kind:   types.StepExec,
			Target: "hyprctl",
			Args:   []string{"keyword", "input:scroll_factor", strconv.FormatFloat(cfg.Mouse.ScrollSpeed, 'f', -1, 64)},
			Desc:   "hyprctl input:scroll_factor " + strconv.FormatFloat(cfg.Mouse.ScrollSpeed, 'f', -1, 64),
		},
		{
			Kind:   types.StepExec,
			Target: "hyprctl",
			Args:   []string{"keyword", "input:touchpad:natural_scroll", strconv.FormatBool(cfg.Trackpad.NaturalScroll)},
			Desc:   "hyprctl input:touchpad:natural_scroll " + strconv.FormatBool(cfg.Trackpad.NaturalScroll),
		},
	}

	return types.Plan{Steps: steps, Warnings: warnings}, nil
}

func buildHyprlandConf(cfg config.Config, sens float64, accelProfile string) string {
	var b strings.Builder
	b.WriteString("# Generated by sensync. Do not edit; this file is overwritten on every `sensync apply`.\n")
	b.WriteString("# Add `source = ~/.config/hypr/sensync.conf` (or wherever this lives) to your hyprland.conf.\n\n")
	b.WriteString("input {\n")
	fmt.Fprintf(&b, "    sensitivity = %s\n", strconv.FormatFloat(sens, 'f', -1, 64))
	fmt.Fprintf(&b, "    accel_profile = %s\n", accelProfile)
	fmt.Fprintf(&b, "    natural_scroll = %s\n", strconv.FormatBool(cfg.Mouse.NaturalScroll))
	fmt.Fprintf(&b, "    scroll_factor = %s\n", strconv.FormatFloat(cfg.Mouse.ScrollSpeed, 'f', -1, 64))
	b.WriteString("\n    touchpad {\n")
	fmt.Fprintf(&b, "        natural_scroll = %s\n", strconv.FormatBool(cfg.Trackpad.NaturalScroll))
	b.WriteString("    }\n")
	b.WriteString("}\n")
	return b.String()
}
